version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./backend/api/Dockerfile
    container_name: homework-api
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080

  db:
    image: postgres:13.1
    container_name: homework-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    # restart: always
    user: root
    ports:
      - 5432:5432

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    container_name: react-app-container
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && yarn start"
    ports:
      - '3000:3000'
