version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: homework-api
    restart: always
    environment:
      - CRYPTO_KEY=passw0rdpassw0rdpassw0rdpassw0rd
    depends_on:
      - db
    ports:
      - 8081:8080

  db:
    image: postgres:13.1
    container_name: homework-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    # restart: always
    user: root
    ports:
      - 5432:5432
